### Variables
@baseUrl = http://localhost:5000/api
@employerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTYzYWQwYjE1MTU0MTE1NTRjY2M5OCIsInJvbGUiOiJFbXBsb3llciIsImlhdCI6MTc3NjY5NjAxNn0.LIfXq8dK-DcJaKY_APeQetKTfRcx9RP8Ji89XWJX4fA
@candidateToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTY1MzEwM2NmMDIxMDcwNjFhNTU0OCIsInJvbGUiOiJDYW5kaWRhdGUiLCJpYXQiOjE3NzY3MDIyMjV9.ZjFSlH0iwalEBJvXUrrlInQ2u2k62ujvo2vLXWepzk4

##############################################
# AUTHENTICATION
##############################################

### Register an Employer
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "Apexcify HR",
    "email": "hr@apexcify.com",
    "password": "password123",
    "role": "Employer",
    "companyDescription": "Leading tech innovators."
}

### Register a Candidate
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "hana Dereje",
    "email": "hana@example.com",
    "password": "password123",
    "role": "Candidate"
}

##############################################
# JOBS (Employer Actions)
##############################################

### Create a New Job (Requires Employer Token)
POST {{baseUrl}}/jobs
Authorization: Bearer {{employerToken}}
Content-Type: application/json

{
    "title": "Senior Django Developer",
    "description": "Develop high-scale REST APIs.",
    "requirements": ["Python", "Django", "PostgreSQL"],
    "salaryRange": "$80k - $120k",
    "location": "Remote",
    "jobType": "Remote"
}

##############################################
# JOBS (Public/Candidate Actions)
##############################################

### Get All Jobs (Public)
GET {{baseUrl}}/jobs

### Filter Jobs by Location & Keyword
GET {{baseUrl}}/jobs?location=Remote&keyword=Senior

##############################################
# APPLICATIONS
##############################################

### Apply for a Job (Candidate Only)
# Note: In REST Client, use 'multipart/form-data' for file uploads. 
# Replace <jobId> with a real ID from the Get Jobs request.
POST {{baseUrl}}/applications/apply/69e64675479f2912dbbdc3e4
Authorization: Bearer {{candidateToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="resume"; filename="cv.pdf"
Content-Type: application/pdf

< C:/Users/MikiyasDereje/Pictures/cv.pdf
--boundary--

### View My Applications (Candidate Only)
GET {{baseUrl}}/applications/my-applications
Authorization: Bearer {{candidateToken}}

### View Applications for a Specific Job (Employer Only)
# Replace <jobId> with the ID of the job you created
GET {{baseUrl}}/applications/jobs/69e63b07b1515411554ccc9a/applications
Authorization: Bearer {{employerToken}}

### Update Application Status (Employer Only)
# Replace <appId> with the actual ID of an application
PATCH {{baseUrl}}/applications/69e653de3cf02107061a5549/status
Authorization: Bearer {{employerToken}}
Content-Type: application/json

{
    "status": "Accepted"
}
